{
 "title": "Fujitsu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "fujitsu_temperature_element", "legendFormat": "{{element}}" }
   ]
  },
  {
   "title": "CPU & Memoryt Temperature",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "fujitsu_temperature_element{element=~\"CPU.\"}",
     "legendFormat": "{{element}}"
    },
    {
     "expr": "fujitsu_temperature_element{element=~\"MEM..\"}",
     "legendFormat": "{{element}}"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "fujitsu_power_overall{max=\"476\"}"
    }
   ]
  }
 ]
}